#theme: jekyll-theme-minimal
# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"
title: "iDaaS Connect"
remote_theme: pmarsceill/just-the-docs
color_scheme: light
search_enabled: false

# https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/#main-navigation
---
layout: default
title: Customization
nav_order: 4
---
# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
markup / liquid-based content.
#footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
footer_content"iDaaS Connect is Part of iDaaS"
