#theme: jekyll-theme-minimal
# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"
title: "iDaaS Connect"
remote_theme: pmarsceill/just-the-docs
color_scheme: light
search_enabled: false
